// start tag. * means that sentence can be repeated 0 to many times.
start: line*

?line: NEWLINE
    | label
    | immediate
    | numeric_val

// statement components
label: IDENTIFIER ":"
immediate: HASH numeric_val
numeric_val: HEX | DEC | BIN


// RAW vals
IDENTIFIER: /[A-Za-z_][A-Za-z0-9_]*/
DEC: /d+/
HEX: /\$[0-9A-Fa-f]+/
BIN: /\%[01]+/
HASH: "#"

%import common.WS_INLINE
%import common.NEWLINE
%ignore WS_INLINE


